### PR TITLE
Update buildDocs.R

### PR DESCRIPTION
**Pull request by XiaosuTong**
Hi Ryan

I found that if I did not do builDocs:::validID, it will get an error saying cannot found validID function.

### CODE REVIEW

**Comment by hafen** [comment]
That's strange... It should be in the namespace.

**Comment by XiaosuTong** [comment]
damn! you are right, it is fine to just have validID. I just did something strange. So sorry about this

**Comment by hafen** [comment]
No problem :).  I'll revert the PR.

**Comment by XiaosuTong** [comment]
Thank you very much

**Pull request merged**
